services: 
  flask:
    image: docker.io/fureasu346/flask:alpine
    environment:
      FLASK_APP: storage_test.py
      FLASK_RUN_PORT: 8000
      DATA_PATH: /app/data/data.txt
    volumes:
    - ./app:/app
    networks:
    - flask_frontend
    ports:
    - "8000:80"
    restart: always

networks:
  flask_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.80.128.0/24
         gateway: 10.80.128.1
