services:
  server:
    image: docker.gitea.com/gitea:1.24.2
    container_name: gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"

networks:
  gitea:

volumes:
  gitea:
    driver: local
