version: "3.9"
services:
  web_green_1:
    image: docker.io/fureasu346/nginx:web
    container_name: web_green_1
    hostname: web_green_1
    volumes:
      - ./web/web_green/web:/var/www/html
      - ./web/web_green/log/1:/var/log/nginx
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - green_backend
    restart: always
  
  web_green_2:
    image: docker.io/fureasu346/nginx:web
    container_name: web_green_2
    hostname: web_green_2
    volumes:
      - ./web/web_green/web:/var/www/html
      - ./web/web_green/log/2:/var/log/nginx
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - green_backend
    restart: always
  
  web_blue_1:
    image: docker.io/fureasu346/nginx:web
    container_name: web_blue_1
    hostname: web_blue_1
    volumes:
      - ./web/web_blue/web:/var/www/html
      - ./web/web_blue/log/1:/var/log/nginx
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blue_backend
    restart: always
  
  web_blue_2:
    image: docker.io/fureasu346/nginx:web
    container_name: web_blue_2
    hostname: web_blue_2
    volumes:
      - ./web/web_blue/web:/var/www/html
      - ./web/web_blue/log/2:/var/log/nginx
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blue_backend
    restart: always

  lb:
    image: docker.io/fureasu346/nginx:lb
    container_name: nginx_lb
    hostname: nginx-lb
    volumes:
      - ./lb/config/certs:/etc/nginx/certs
      - ./lb/config/https-nginx.conf:/etc/nginx/nginx.conf
      - ./lb/log:/var/log/nginx
    networks:
      - frontend
      - green_backend
      - blue_backend
    ports:
      - "8000:80"
      - "9000:443"
    restart: always
    depends_on:
      - web_green_1
      - web_green_2
      - web_blue_1
      - web_blue_2

networks:
  green_backend:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.100.1.0/24
          gateway: 10.100.1.1
  blue_backend:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.100.2.0/24
          gateway: 10.100.2.1
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.99.0.0/24
          gateway: 10.99.0.1
