version: "3.9"
services:
  web_green_1:
    image: docker.io/fureasu346/nginx:web
    container_name: web_green_1
    hostname: web_green_1
    volumes:
      - ./web_green:/var/www/html
    networks:
      - green_backend
    restart: always
  
  web_green_2:
    image: docker.io/fureasu346/nginx:web
    container_name: web_green_2
    hostname: web_green_2
    volumes:
      - ./web_green:/var/www/html
    networks:
      - green_backend
    restart: always
  
  web_blue_1:
    image: docker.io/fureasu346/nginx:web
    container_name: web_blue_1
    hostname: web_blue_1
    volumes:
      - ./web_blue:/var/www/html
    networks:
      - blue_backend
    restart: always
  
  web_blue_2:
    image: docker.io/fureasu346/nginx:web
    container_name: web_blue_2
    hostname: web_blue_2
    volumes:
      - ./web_blue:/var/www/html
    networks:
      - blue_backend
    restart: always

  lb:
    image: docker.io/fureasu346/nginx:lb
    container_name: nginx_lb
    hostname: nginx-lb
    volumes:
      - ./lb:/config
    networks:
      - frontend
      - green_backend
      - blue_backend
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - web_green_1
      - web_blue_1
    command: /config/nginx_start.sh

networks:
  green_backend:
    driver: bridge
    internal: true
  blue_backend:
    driver: bridge
    internal: true
  frontend:
    driver: bridge
