version: "3.8"
services:
  web:
    build: web
    container_name: websvr
    hostname: websvr
    ports:
      - "7000:80"
    volumes:
      - ./web/www:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - db
    restart: always
    
  db:
    build: db
    container_name: dbsvr
    environment:
      MYSQL_ROOT_PASSWORD: root_P@ssw0rd
      MYSQL_USERNAME: webadmin
      MYSQL_USER_PASSWORD: webadmin_P@ssw0rd
      MYSQL_REMOTE_HOST: '%'
    hostname: dbsvr
    volumes:
      - ./db/queries:/home/ubuntu/queries
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
